### ISSUE TITLE
Unexpected errors - The operation was canceled

### ISSUE THREAD

**Issue by iminder-singh** [reportportal/agent-net-gauge#30]
To give some background, gauge tests were run on jenkins which is hosted in the cloud. Reportportal is hosted on a VM on a different network. It may be that I need to speak to DevOps team to check that this VM can be accessed from jenkins in the cloud (it should be as I did ask them to allow it) but I would have expected a time out message or something similar instead of an unexpected error. Though it may be a different issue. See stack trace below:

>Finishing to send results to Report Portal...
Unexpected errors: System.Threading.Tasks.TaskCanceledException: The operation was canceled.
at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean ********Http2, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
at ReportPortal.Client.Resources.ServiceBaseResource.SendAsJsonAsync[TResponse,TRequest](HttpMethod httpMethod, String uri, TRequest request)
at ReportPortal.Client.Resources.ServiceBaseResource.PostAsJsonAsync[TResponse,TRequest](String uri, TRequest request)
at ReportPortal.Client.Resources.ServiceLaunchResource.StartAsync(StartLaunchRequest request)
at ReportPortal.Shared.Internal.Delegating.ExponentialRetryRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttempt)
at ReportPortal.Shared.Internal.Delegating.ExponentialRetryRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttempt)
at ReportPortal.Shared.Reporter.LaunchReporter.<>c__DisplayClass20_0.<<Start>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at ReportPortal.Shared.Reporter.LaunchReporter.Sync()
at ReportPortal.GaugePlugin.Results.Sender.Sync()
at ReportPortal.GaugePlugin.ReportMessagesHandler.Kill(KillProcessRequest request, ServerCallContext context)

**Comment by nvborisenko** [comment]
This is timeout exception.

**Comment by iminder-singh** [comment]
This happened because of firewall issues so I'll close this.
