### ISSUE TITLE
Getting this error: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by mathew-jithinm** [reportportal/agent-net-gauge#56]
Getting this error randomly during many runs. Hope you will please have a check @nvborisenko 

```
Finishing to send results to Report Portal...
Unexpected error: System.NullReferenceException: Object reference not set to an instance of an object.
at ReportPortal.GaugePlugin.Results.Sender.Sync()
at ReportPortal.GaugePlugin.Services.ReportMessagesHandler.Kill(KillProcessRequest request, ServerCallContext context)
fail: Grpc.AspNetCore.Server.ServerCallHandler[6]
Error when executing service method 'Kill'.
System.NullReferenceException: Object reference not set to an instance of an object.
at ReportPortal.GaugePlugin.Services.ReportMessagesHandler.Kill(KillProcessRequest request, ServerCallContext context)
at Grpc.Shared.Server.UnaryServerMethodInvoker`3.Invoke(HttpContext , ServerCallContext , TRequest )
--- End of stack trace from previous location ---
at Grpc.AspNetCore.Server.Internal.CallHandlers.UnaryServerCallHandler`3.HandleCallAsyncCore(HttpContext , HttpContextServerCallContext )
at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase`3.<HandleCallAsync>g__AwaitHandleCall|8_0(HttpContextServerCallContext , Method`2 , Task )
```

**Comment by nvborisenko** [comment]
This issue can be easily fixed, but I should reproduce it. @mathew-jithinm can you elaborate more about how it happens, any specific conditions?

I can assume your launch consists of skipped scenarios only. Can you please share output from gauge about final results (count of passed/failed/skipped)?

**Comment by mathew-jithinm** [comment]
Sure @nvborisenko I forgot to save the last set of logs. Will share the same once it happens again.

Like you guessed, it happens mainly when skipped/failed scenarios are only present.

**Comment by nvborisenko** [comment]
@mathew-jithinm is it still reproducible?

**Comment by nvborisenko** [comment]
Please reopen it if it's still actual.
