### ISSUE TITLE
Finish launch is not allowed. Launch '<launch_id>' already finished with status 'PASSED'

### ISSUE THREAD

**Issue by mathew-jithinm** [reportportal/agent-net-gauge#57]
@nvborisenko Getting the following error after execution (auto-generated).

1. Not sure how the test was marked as `Passed`/`Finished` before the final `finish` call (test was not timed-out).
2. Is it possible we can add an error handling here?

There were no skipped cases, but a few set of failed cases were present.

```
Finishing to send results to Report Portal...
Unexpected error: ReportPortal.Client.ReportPortalException: Response status code does not indicate success: NotAcceptable (406) PUT <url>/api/v1/<project>/launch/<launch_id>/finish
---> System.Net.Http.HttpRequestException: Response message: {"errorCode":40023,"message":"Finish launch is not allowed. Launch '<launch_id>' already finished with status 'PASSED'"}
--- End of inner exception stack trace ---
at ReportPortal.Client.Resources.ServiceBaseResource.CheckSuccessStatusCode(HttpResponseMessage response, Stream stream)
at ReportPortal.Client.Resources.ServiceBaseResource.SendHttpRequestAsync[TResponse](HttpMethod httpMethod, String uri, HttpContent httpContent)
at ReportPortal.Shared.Internal.Delegating.BaseRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttemptCallback, IStatisticsCounter statisticsCounter)
at ReportPortal.Shared.Internal.Delegating.ExponentialRetryRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttempt, IStatisticsCounter statisticsCounter)
at ReportPortal.Shared.Reporter.LaunchReporter.<>c__DisplayClass30_0.<<Finish>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at ReportPortal.Shared.Reporter.LaunchReporter.Sync()
at ReportPortal.GaugePlugin.Results.Sender.Sync()
at ReportPortal.GaugePlugin.Services.ReportMessagesHandler.Kill(KillProcessRequest request, ServerCallContext context)
```

**Comment by nvborisenko** [comment]
Omg, this is something for hard resolving. You should specify conditions when you meet this error, any retries, any other specific runner parameters?

In any case I would like to see reproducible test project.

**Comment by nvborisenko** [comment]
@mathew-jithinm is it still reproducible?

**Comment by nvborisenko** [comment]
Please reopen it if it's still actual.
